#!/usr/local/cpanel/3rdparty/bin/perl

# cpanel - libexec/on_boot/populate_system_needs_reboot
#                                                  Copyright 2022 cPanel, L.L.C.
#                                                           All rights reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package libexec::on_boot::populate_system_needs_reboot;

use strict;
use warnings;

use Cpanel::ServerTasks ();

sub script {
    Cpanel::ServerTasks::schedule_task( ['SystemTasks'], 5, "recache_system_reboot_data" );
    return 0;
}

exit( script(@ARGV) ? 0 : 1 ) unless caller();

1;
